const vietToKatakanaMap: Record<string, string> = {
  an: 'アン',
  anh: 'アイン',
  ba: 'バ',
  bac: 'バック',
  bach: 'バック',
  bang: 'バーン',
  bao: 'バオ',
  bay: 'バイ',
  be: 'ベ',
  beo: 'ベオ',
  bich: 'ビック',
  binh: 'ビン',
  bo: 'ボー',
  bui: 'ブイ',
  buu: 'ビュウ',
  cam: 'カム',
  canh: 'カイン',
  cao: 'カオ',
  cham: 'チャム',
  chanh: 'チャイン',
  chau: 'チャウ',
  che: 'チェー',
  chi: 'チー',
  chien: 'チエン',
  chieu: 'チエウ',
  chuong: 'チュオン',
  co: 'コー',
  cong: 'コン',
  cuc: 'クック',
  cuong: 'クオン',
  da: 'ヤ',
  danh: 'ヤン',
  di: 'ジー',
  diem: 'ジエム',
  dieu: 'ジエウ',
  diep: 'ジエップ',
  doan: 'ヨアン',
  doanh: 'ヨアイン',
  du: 'ユー',
  dung: 'ズン',
  duong: 'ズオン',
  duy: 'ズイ',
  duyen: 'ズエン',
  đai: 'ダイ',
  đam: 'ダム',
  đang: 'ダン',
  đao: 'ダオ',
  đat: 'ダット',
  đe: 'デー',
  đen: 'デン',
  đien: 'ディエン',
  điep: 'ディエップ',
  đieu: 'ディエウ',
  đinh: 'ディン',
  đo: 'ドー',
  đoan: 'ドアン',
  đoc: 'ドック',
  đong: 'ドン',
  đuc: 'ドゥック',
  đuoc: 'ドゥオク',
  em: 'エム',
  gam: 'ガム',
  gia: 'ジャー',
  giam: 'ガム',
  giang: 'ジャン',
  giap: 'ジャップ',
  giau: 'ジャウ',
  ha: 'ハー',
  hai: 'ハイ',
  han: 'ハン',
  hang: 'ハン',
  hanh: 'ハイン',
  hao: 'ハオ',
  hau: 'ハウ',
  hien: 'ヒエン',
  hiep: 'ヒエップ',
  hieu: 'ヒュー',
  ho: 'ホー',
  hoa: 'ホア',
  hoai: 'ホアイ',
  hoang: 'ホアン',
  hoc: 'ホック',
  hoi: 'ホイ',
  hong: 'ホン',
  hua: 'フア',
  huan: 'フアン',
  hue: 'フェ',
  hung: 'フーン',
  huong: 'フーン',
  huu: 'フウ',
  huy: 'フイ',
  huyen: 'フエン',
  huynh: 'フイン',
  kha: 'カー',
  khac: 'カック',
  khai: 'カイ',
  khanh: 'カイン',
  khien: 'キエン',
  khoa: 'コア',
  khuc: 'クーク',
  khuong: 'クオン',
  kien: 'キエン',
  kiet: 'キエット',
  kim: 'キム',
  kinh: 'キン',
  ky: 'キー',
  la: 'ラ',
  lac: 'ラック',
  lai: 'ライ',
  lam: 'ラーム',
  lan: 'ラン',
  lanh: 'ライン',
  le: 'レー',
  liem: 'リエム',
  lien: 'リエン',
  lieu: 'リエウ',
  linh: 'リン',
  loan: 'ロアン',
  loc: 'ロック',
  loi: 'ロイ',
  long: 'ロン',
  luat: 'ルアット',
  luong: 'ルオン',
  luu: 'リュー',
  luc: 'ルック',
  luy: 'ルイ',
  ly: 'リー',
  mai: 'マイ',
  man: 'マン',
  mang: 'マン',
  manh: 'マイン',
  men: 'メン',
  meo: 'メオ',
  minh: 'ミン',
  mo: 'モー',
  mong: 'モン',
  mui: 'ムイ',
  muoi: 'ムオイ',
  my: 'ミー',
  na: 'ナ',
  nam: 'ナム',
  nang: 'ナン',
  nga: 'ガー',
  ngan: 'ガン',
  nghi: 'ギー',
  nghia: 'ギア',
  nghiep: 'ギエップ',
  ngo: 'ズイ',
  ngoc: 'ゴック',
  ngu: 'グー',
  nguyen: 'グエン',
  nguyet: 'グエット',
  nha: 'ニャー',
  nhan: 'ニャン',
  nhat: 'ニャット',
  nhi: 'ニー',
  nhieu: 'ニエウ',
  nho: 'ニョー',
  nhon: 'ニョン',
  nhu: 'ヌー',
  nhung: 'ニュン',
  nhuong: 'ニュオン',
  nhut: 'ニュット',
  ninh: 'ニン',
  noi: 'ノイ',
  oanh: 'オアン',
  pha: 'ファー',
  pham: 'ファム',
  phan: 'ファン',
  phat: 'ファット',
  phi: 'フイ',
  phong: 'フォン',
  phu: 'フー',
  phuc: 'フック',
  phung: 'フーン',
  phuoc: 'フオック',
  phuong: 'フォン',
  quan: 'クアン',
  quang: 'クアン',
  qui: 'クイ',
  quoc: 'クオック',
  quy: 'クイ',
  que: 'クエ',
  quyen: 'クエン',
  quyet: 'クエット',
  quynh: 'クイン',
  sam: 'サム',
  san: 'サン',
  sang: 'サン',
  si: 'シー',
  sieu: 'シエウ',
  sinh: 'シン',
  son: 'ソン',
  su: 'スー',
  sua: 'スア',
  sung: 'スン',
  suong: 'スオン',
  sy: 'シー',
  ta: 'ター',
  tac: 'タック',
  tai: 'タイ',
  tam: 'タム',
  tan: 'タン',
  tang: 'タン',
  tat: 'タット',
  tay: 'タイ',
  thach: 'タック',
  thai: 'ターイ',
  tham: 'ターム',
  than: 'タン',
  thang: 'ターン',
  thanh: 'タイン',
  thao: 'タオ',
  the: 'テー',
  thi: 'ティ',
  thien: 'ティエン',
  thiet: 'ティエット',
  thieu: 'ティエウ',
  thinh: 'ティン',
  tho: 'トー',
  thoai: 'トアイ',
  thom: 'トム',
  thong: 'トン',
  thu: 'トゥー',
  thuat: 'トゥアット',
  thuan: 'トゥアン',
  thuc: 'トゥック',
  thuong: 'トゥオン',
  thuy: 'トゥイ',
  thuyen: 'トゥエン',
  thuyet: 'トゥイット',
  tiem: 'ティエム',
  tien: 'ティエン',
  tiet: 'ティエット',
  tin: 'ティン',
  tinh: 'ティン',
  to: 'トー',
  toan: 'トアン',
  toi: 'トイ',
  tong: 'トン',
  tra: 'チャ',
  trac: 'チャック',
  tram: 'チャム',
  tran: 'チャン',
  tri: 'チー',
  trien: 'チエン',
  triet: 'チエット',
  trieu: 'チーウ',
  trinh: 'チン',
  trong: 'チョン',
  tru: 'チュー',
  truc: 'チュック',
  trung: 'チュン',
  truong: 'チュオン',
  tu: 'トゥー',
  tuan: 'トゥアン',
  tung: 'トゥン',
  tuoi: 'トゥオイ',
  tuong: 'トゥオン',
  tuot: 'トゥオット',
  tuyen: 'トゥェン',
  tuyet: 'トゥエット',
  ty: 'テイ',
  ut: 'ウット',
  uyen: 'ウエン',
  van: 'バン',
  vang: 'バン',
  vien: 'ビエン',
  viet: 'ビエット',
  vinh: 'ビン',
  vo: 'ボー',
  vu: 'ブー',
  vuong: 'ブオン',
  vy: 'ビー',
  xu: 'スー',
  xuan: 'スアン',
  xum: 'スム',
  xung: 'スン',
  xuyen: 'スエン',
  y: 'イー',
  yen: 'イエン',
};

const removeVietnameseTones = (str: string): string => {
  if(str.toLocaleLowerCase() === "hưng" ){
      return "フン";
  } 
  if(str.toLocaleLowerCase() === "thư" ){
      return "トゥ";
  }
  // Bước 1: Tạm thời thay đ/Đ bằng ký hiệu tạm để không bị mất khi normalize
  const placeholder = '__D_PLACEHOLDER__';
  str = str.replace(/đ/g, placeholder).replace(/Đ/g, placeholder.toUpperCase());

  // Bước 2: Loại bỏ các dấu thanh bằng Unicode normalize
  str = str.normalize('NFD').replace(/[\u0300-\u036f]/g, '');

  // Bước 3: Khôi phục lại đ/Đ
  str = str
    .replace(new RegExp(placeholder, 'g'), 'đ')
    .replace(new RegExp(placeholder.toUpperCase(), 'g'), 'Đ');

  return str;
};

export const convertToKatakana = (vietnameseName: string): string => {
  
  const normalized = removeVietnameseTones(vietnameseName.toLowerCase());
  const syllables = normalized.split(/\s+/);

  const katakanaParts = syllables.map((syllable) => vietToKatakanaMap[syllable] || syllable);

  return katakanaParts.join('・'); // dùng dấu ・ như trong cách viết Katakana tên nước ngoài
};
